import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { addWorkshopExpense, completeWorkshopJob, createWorkshopJob, reportMaintenanceIssue, resolveMaintenanceHold, saveInspectionReadings, saveWorkshopIssue, saveWorkshopProgress, updateWorkshopCheck, updateWorkshopDueAt, uploadIssuePhoto, uploadReadyPhoto, type WorkshopCheck } from "./actions";
import WorkshopReturnLink from "./workshop-return-link";
import "./workshop.css";

type Vehicle={id:string;year:number|null;make:string|null;model:string|null;license_plate:string|null;status:string};
type WorkshopJob={id:string;vehicle_id:string;status:string;due_at:string|null;checklist:WorkshopCheck[];ready_photos:string[];notes:string;odometer:number|null;fuel_level:number|null;created_at:string;completed_at:string|null;vehicles:Vehicle|null};
const closed=new Set(["completed","ready"]);
function withPhysicalDamage(checklist:WorkshopCheck[]){if(checklist.some(item=>item.key==="physical_damage"))return checklist;const item:WorkshopCheck={key:"physical_damage",label:"Inspect and document physical vehicle damage",group:"Exterior",status:"pending"};const index=checklist.findIndex(entry=>entry.key==="exterior");return index<0?[...checklist,item]:[...checklist.slice(0,index+1),item,...checklist.slice(index+1)];}

export default async function FleetWorkshopPage({searchParams}:{searchParams:Promise<{job?:string;from?:string;error?:string;started?:string;hold?:string;completed?:string;photo?:string;saved?:string}>}){
  const query=await searchParams;
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();
  if(!user) redirect("/login");
  const {data:membership}=await supabase.from("organization_members").select("organization_id,role,organizations(name)").eq("user_id",user.id).limit(1).maybeSingle();
  if(!membership) redirect("/login");
  const [{data:vehicles},{data:jobs,error}]=await Promise.all([
    supabase.from("vehicles").select("id,year,make,model,license_plate,status").eq("organization_id",membership.organization_id).order("year",{ascending:false}),
    supabase.from("fleet_workshop_jobs").select("id,vehicle_id,status,due_at,checklist,ready_photos,notes,odometer,fuel_level,created_at,completed_at,vehicles(id,year,make,model,license_plate,status)").eq("organization_id",membership.organization_id).order("created_at",{ascending:false}),
  ]);
  const vehicleRows=(vehicles??[]) as Vehicle[];
  const jobRows=((jobs??[]) as unknown as WorkshopJob[]).map(job=>({...job,checklist:withPhysicalDamage(job.checklist??[])}));
  const activeJobs=jobRows.filter(job=>!closed.has(job.status));
  const selected=jobRows.find(job=>job.id===(query.job??activeJobs[0]?.id));
  const checklist=selected?.checklist??[];
  const checklistGroups=Array.from(new Set(checklist.map(item=>item.group))).map(group=>({group,items:checklist.filter(item=>item.group===group)}));
  const passed=checklist.filter(item=>item.status==="passed").length;
  const readyPhotos=(selected?.ready_photos??[]).map(path=>supabase.storage.from("workshop-photos").getPublicUrl(path).data.publicUrl);
  const issuePhotoUrls=new Map(checklist.flatMap(item=>(item.issuePhotos??[]).map(path=>[path,supabase.storage.from("workshop-photos").getPublicUrl(path).data.publicUrl] as const)));
  const organization=membership.organizations as unknown as {name?:string}|null;
  const fallbackOrigin=membership.role==="porter"?"porter":membership.role==="viewer"?"intelligence":"command";
  const returnHref=query.from==="intelligence"?"/dashboard/vehicle-intelligence":query.from==="calendar"?"/dashboard/smart-calendar":fallbackOrigin==="porter"?"/dashboard/fleet-workshop":"/dashboard/command-center";
  const returnLabel=query.from==="intelligence"?"Return to Vehicle Intelligence":query.from==="calendar"?"Return to Smart Calendar":fallbackOrigin==="porter"?"Return to porter queue":"Return to Command Center";
  return <main className="workshop-shell">
    <header className="workshop-top"><WorkshopReturnLink initialOrigin={query.from} fallbackOrigin={fallbackOrigin}/><div><strong>Porter Operations</strong><span>{organization?.name??"Check Calling"}</span></div><Link href="/dashboard/smart-calendar">Smart Calendar</Link></header>
    <section className="workshop-hero"><div><div className="workshop-eyebrow">Mobile turnaround operations</div><h1>Return. Inspect. Reset. Release.</h1><p>One guided workspace for porters to prepare every returned vehicle for its next rental.</p></div><div className="workshop-live"><strong>{activeJobs.length}</strong><span>active turnaround{activeJobs.length===1?"":"s"}</span></div></section>
    {(query.error||error)&&<div className="workshop-message error">{query.error||error?.message}</div>}{query.started&&<div className="workshop-message success">✓ Turnaround started and saved. The vehicle is unavailable until final release.</div>}{query.saved==="check"&&<div className="workshop-message success">✓ Inspection checklist update saved.</div>}{query.saved==="issue"&&<div className="workshop-message success">✓ Issue type and porter note saved.</div>}{query.saved==="readings"&&<div className="workshop-message success">✓ Odometer and fuel or charge level saved to the fleet record.</div>}{query.saved==="due"&&<div className="workshop-message success">✓ This vehicle’s ready-by date and time were saved to the Workshop and Smart Calendar.</div>}{query.saved==="maintenance"&&<div className="workshop-message success">✓ Maintenance work marked complete. The vehicle is back in final inspection.</div>}{query.saved==="expense"&&<div className="workshop-message success">✓ Workshop expense saved to Fleet Finance and shared vehicle intelligence.</div>}{query.saved==="progress"&&<div className="workshop-message success">✓ Workshop progress saved. You can safely select another vehicle or return later.</div>}{query.photo==="issue"&&<div className="workshop-message success">✓ Issue photo uploaded and attached to the inspection.</div>}{query.photo&&query.photo!=="issue"&&<div className="workshop-message success">✓ Clean-and-ready photo uploaded successfully.</div>}{query.hold&&<div className="workshop-message warning">Maintenance hold created and shared with the calendar and fleet record.</div>}{query.completed&&<div className="workshop-message success completion-message"><span>✓ Vehicle released and marked ready for its next rental.</span><Link href={returnHref}>{returnLabel}</Link></div>}
    <section className="workshop-kpis"><article><span>Returned</span><strong>{activeJobs.filter(job=>job.status==="returned").length}</strong></article><article><span>In progress</span><strong>{activeJobs.filter(job=>["in_progress","final_review"].includes(job.status)).length}</strong></article><article className="warn"><span>Issues</span><strong>{activeJobs.filter(job=>["issue_found","maintenance_hold"].includes(job.status)).length}</strong></article><article><span>Ready today</span><strong>{jobRows.filter(job=>closed.has(job.status)&&job.completed_at&&new Date(job.completed_at).toDateString()===new Date().toDateString()).length}</strong></article></section>
    <div className="workshop-layout"><aside className="workshop-queue"><div className="workshop-card-head"><div><div className="workshop-eyebrow">Porter queue</div><h2>Vehicles to prepare</h2></div></div><form action={createWorkshopJob} className="start-job"><label>Returned vehicle<select name="vehicle_id" required defaultValue=""><option value="" disabled>Select vehicle</option>{vehicleRows.map(vehicle=><option value={vehicle.id} key={vehicle.id}>{vehicle.year} {vehicle.make} {vehicle.model} · {vehicle.license_plate??"no plate"}</option>)}</select></label><button>Start inspection</button></form><div className="job-list">{activeJobs.map(job=><Link href={`/dashboard/fleet-workshop?job=${job.id}`} className={selected?.id===job.id?"active":""} key={job.id}><span className={`job-dot ${job.status}`}/><div><strong>{job.vehicles?.year} {job.vehicles?.make} {job.vehicles?.model}</strong><small>{job.vehicles?.license_plate??"Plate missing"} · {job.status.replaceAll("_"," ")}{job.due_at?` · do not rent until ${new Date(job.due_at).toLocaleString()}`:" · readiness date required — do not rent"}</small></div><em>{(job.checklist??[]).filter(item=>item.status==="passed").length}/{(job.checklist??[]).length}</em></Link>)}{!activeJobs.length&&<div className="workshop-empty">No vehicles are waiting. Start a turnaround when a rental is returned.</div>}</div></aside>
      <section className="workshop-job">{selected ? <>
        <header><div><div className="workshop-eyebrow">Active turnaround</div><h2>{selected.vehicles?.year} {selected.vehicles?.make} {selected.vehicles?.model}</h2><p>{selected.vehicles?.license_plate??"Plate missing"} · <b className="rental-hold-copy">{selected.due_at?`Do not rent until ${new Date(selected.due_at).toLocaleString()}`:"Readiness date required — do not rent"}</b></p></div><form className="vehicle-ready-by" action={updateWorkshopDueAt.bind(null,selected.id)}><label>Estimated ready by<input type="datetime-local" name="due_at" defaultValue={selected.due_at?new Date(new Date(selected.due_at).getTime()-new Date(selected.due_at).getTimezoneOffset()*60000).toISOString().slice(0,16):""} required /></label><button>Update readiness</button></form><span className={`workshop-status ${selected.status}`}>{selected.status.replaceAll("_"," ")}</span></header>
        <div className="workshop-progress"><i style={{width:`${checklist.length?passed/checklist.length*100:0}%`}}/><span>{passed} of {checklist.length} checks passed</span></div>
        <form className="inspection-readings" action={saveInspectionReadings.bind(null,selected.id)}><div><div className="workshop-eyebrow">Return readings</div><strong>Record verified check-in values</strong></div><label>Odometer<input name="odometer" type="number" min="0" step="1" defaultValue={selected.odometer??""} inputMode="numeric" required /></label><label>Fuel / charge<select name="fuel_level" defaultValue={selected.fuel_level??""} required><option value="" disabled>Select level</option><option value="0">Empty</option><option value="25">¼ tank / charge</option><option value="50">½ tank / charge</option><option value="75">¾ tank / charge</option><option value="100">Full</option></select></label><button>Save readings</button></form>
        <div className="inspection-groups">{checklistGroups.map((section,groupIndex)=>{const groupPassed=section.items.filter(item=>item.status==="passed").length;const hasIssue=section.items.some(item=>item.status==="issue");return <details className={`inspection-group ${hasIssue?"has-issue":groupPassed===section.items.length?"complete":""}`} open={hasIssue||groupIndex===0} key={section.group}><summary><span><small>Inspection category</small><strong>{section.group}</strong></span><em>{hasIssue?"Issue found":`${groupPassed}/${section.items.length} passed`}</em></summary><div className="porter-checklist">{section.items.map((item,index)=><article className={item.status} key={item.key}><span className="check-number">{item.status==="passed"?"✓":item.status==="issue"?"!":index+1}</span><div><small>{item.group}</small><strong>{item.label}</strong>{item.issueNote&&<p>{item.issueType?.replaceAll("_"," ")} · {item.issueNote} <em className="saved-chip">✓ Saved</em></p>}</div><div className="check-actions"><form action={updateWorkshopCheck.bind(null,selected.id,item.key,"passed")}><button className="pass">Pass</button></form><form action={updateWorkshopCheck.bind(null,selected.id,item.key,"issue")}><button className="issue">Issue</button></form></div></article>)}</div></details>})}</div>
        {checklist.filter(item=>item.status==="issue").map(item=><details className="issue-followup" open={!item.issueNote} key={`${selected.id}-${item.key}`}><summary>{item.issueNote?"Saved issue evidence":"Add details for"}: {item.label}</summary>{!item.issueNote&&<form action={saveWorkshopIssue.bind(null,selected.id,item.key)}><label>Issue type<select name="issue_type" defaultValue="" required><option value="" disabled>Select the finding</option><option value="cleaning">Cleaning not complete</option><option value="damage">New vehicle damage</option><option value="missing_item">Missing key, document, or equipment</option><option value="odor">Smoke, odor, or stain</option><option value="tire_glass">Tire, wheel, or glass problem</option><option value="warning_light">Warning light</option><option value="fluid_leak">Fluid leak</option><option value="mechanical">Mechanical or safety concern</option><option value="other">Other issue</option></select></label><label>Porter note<textarea name="issue_note" rows={3} defaultValue="" required placeholder="Describe what you found and where it is on the vehicle." /></label><button>Save issue details</button></form>}<form className="issue-photo-form" action={uploadIssuePhoto.bind(null,selected.id,item.key)}><label>Photo evidence<input name="issue_photo" type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" capture="environment" required /></label><button>Upload issue photo</button></form>{Boolean(item.issuePhotos?.length)&&<div className="ready-photo-strip">{item.issuePhotos!.map(path=><img src={issuePhotoUrls.get(path)} alt={`Evidence for ${item.label}`} key={path}/>)}</div>}</details>)}
        <div className="workshop-support-grid"><section className="ready-evidence"><div><div className="workshop-eyebrow">Ready-for-rent evidence</div><h3>Upload the clean vehicle photo</h3><p>This photo becomes the host’s proof that the wash and final reset were completed.</p></div><form action={uploadReadyPhoto.bind(null,selected.id)}><label className="camera-upload"><span>Open camera or choose photo</span><input name="ready_photo" type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" capture="environment" required /></label><button>Upload ready photo</button></form>{readyPhotos.length>0&&<div className="ready-photo-strip">{readyPhotos.map((url,index)=><img src={url} alt={`Clean and ready evidence ${index+1}`} key={url}/>)}</div>}</section><div className="workshop-support-actions">
        {selected.status==="maintenance_hold"?<section className="maintenance-resolution"><div><div className="workshop-eyebrow">Maintenance hold active</div><h3>Repair must be completed before release</h3><p>{selected.notes}</p></div>{["owner","admin","host"].includes(membership.role)&&<form action={resolveMaintenanceHold.bind(null,selected.id)}><button>Mark maintenance complete</button></form>}</section>:<details className="maintenance-escalation" open={checklist.some(item=>item.status==="issue"&&["warning_light","fluid_leak","mechanical","tire_glass"].includes(item.issueType??""))}><summary>Escalate a mechanical or safety issue</summary><form action={reportMaintenanceIssue.bind(null,selected.id)}><label>Severity<select name="severity"><option value="inspect">Needs inspection</option><option value="service">Service required</option><option value="unsafe">Unsafe — do not rent</option></select></label><label>What did you find?<textarea name="summary" rows={3} required placeholder="Example: Oil visible beneath the engine after return." /></label><button>Create maintenance hold</button></form></details>}
        {["owner","admin","host"].includes(membership.role)&&<details className="workshop-expense"><summary>Record a Workshop expense in Fleet Finance</summary><form action={addWorkshopExpense.bind(null,selected.id)}><label>Expense type<select name="category"><option value="maintenance">Routine maintenance</option><option value="repair">Repair</option></select></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" inputMode="decimal" required /></label><label className="expense-description">Description<input name="description" maxLength={500} placeholder="Wash, part, outside service, or repair" /></label><button>Save to Fleet Finance</button></form></details>}</div></div>
        <form className="save-workshop-progress" action={saveWorkshopProgress.bind(null,selected.id)}><div><strong>Finished for now?</strong><span>Save all current inspection progress before leaving or selecting another vehicle.</span></div><button>Save workshop progress</button></form>
        <form className="release-job" action={completeWorkshopJob.bind(null,selected.id)}><p>Release requires every check to pass and at least one clean-and-ready photo.</p><button disabled={passed!==checklist.length||selected.status==="maintenance_hold"||!readyPhotos.length}>Mark vehicle ready</button></form>
      </> : <div className="workshop-empty large"><strong>Select or start a turnaround</strong><span>The guided porter checklist will appear here.</span></div>}</section></div>
    <nav className="workshop-mobile-nav"><Link href="/dashboard/command-center">Today</Link><Link className="active" href="/dashboard/fleet-workshop">Workshop</Link><Link href="/dashboard/smart-calendar">Calendar</Link><Link href="/dashboard/vehicle-intelligence">Fleet</Link></nav>
  </main>;
}
