"use client";
import {useState} from "react";
import {saveAgreementRules} from "./actions";

export type AgreementRules={source?:string;stockTemplate?:string;companyName?:string;jurisdiction?:string;lateFee?:string;mileageAllowance?:string;fuelPolicy?:string;customTerms?:string;signatureProvider?:string;sendTiming?:string;reminderHours?:number;requireSignature?:boolean;requirePayment?:boolean;requireDeposit?:boolean;requireInspection?:boolean;includeEvaluationSummary?:boolean;uploadedAgreement?:{name?:string;path?:string}};
const templates=[{id:"standard",name:"Standard Vehicle Rental Agreement",description:"A general short-term agreement covering vehicle use, payment, responsibility, return, and prohibited activity."},{id:"weekly_monthly",name:"Weekly & Monthly Rental Agreement",description:"Adds recurring billing, renewal, mileage periods, late payment, and long-term vehicle care terms."},{id:"commercial",name:"Commercial & Work-Use Agreement",description:"Adds authorized drivers, business use, jobsite restrictions, equipment, and commercial responsibility terms."}];

export default function AgreementForm({rules,organizationName}:{rules:AgreementRules;organizationName:string}){
  const [source,setSource]=useState(rules.source??"stock");const [template,setTemplate]=useState(rules.stockTemplate??"standard");const [company,setCompany]=useState(rules.companyName??organizationName);
  const selected=templates.find(item=>item.id===template)??templates[0];
  return <form action={saveAgreementRules} className="agreement-form">
    <section className="agreement-card"><div className="agreement-card-head"><div><span>Agreement source</span><h2>Choose a reusable starting point</h2></div><em>Company ready</em></div><div className="source-options"><label className={source==="stock"?"selected":""}><input type="radio" name="agreementSource" value="stock" checked={source==="stock"} onChange={()=>setSource("stock")}/><span><strong>Check Calling stock agreement</strong><small>Use a structured, fill-in template included with the platform.</small></span></label><label className={source==="upload"?"selected":""}><input type="radio" name="agreementSource" value="upload" checked={source==="upload"} onChange={()=>setSource("upload")}/><span><strong>Upload your own agreement</strong><small>Use an existing company PDF or DOCX agreement.</small></span></label></div>{source==="stock"?<div className="template-grid">{templates.map(item=><label className={template===item.id?"selected":""} key={item.id}><input type="radio" name="stockTemplate" value={item.id} checked={template===item.id} onChange={()=>setTemplate(item.id)}/><span><strong>{item.name}</strong><small>{item.description}</small></span></label>)}</div>:<div className="upload-box"><label>Agreement document<input name="agreementFile" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document"/></label><p>PDF or DOCX · Maximum 10 MB</p>{rules.uploadedAgreement?.name&&<div className="current-file">Current document: <strong>{rules.uploadedAgreement.name}</strong></div>}</div>}</section>
    <section className="agreement-layout"><div className="agreement-card"><div className="agreement-card-head"><div><span>Fill-in agreement</span><h2>Company and rental terms</h2></div><em>Reusable fields</em></div><div className="agreement-fields"><label>Company name<input name="companyName" value={company} onChange={e=>setCompany(e.target.value)} required/></label><label>Governing state or jurisdiction<input name="jurisdiction" defaultValue={rules.jurisdiction} placeholder="California"/></label><label>Late-return fee<input name="lateFee" defaultValue={rules.lateFee} placeholder="$50 per hour"/></label><label>Mileage allowance<input name="mileageAllowance" defaultValue={rules.mileageAllowance} placeholder="200 miles per day"/></label><label>Fuel policy<select name="fuelPolicy" defaultValue={rules.fuelPolicy??"same_level"}><option value="same_level">Return at the same fuel level</option><option value="full">Return with a full tank</option><option value="included">Fuel included in rental</option></select></label><label className="full">Additional company terms<textarea name="customTerms" rows={5} defaultValue={rules.customTerms} placeholder="Add company-specific rules, prohibited uses, cleaning requirements, or return instructions."/></label></div></div><aside className="agreement-preview"><span>{source==="stock"?"Live stock preview":"Uploaded agreement mapping"}</span><h2>{source==="stock"?selected.name:(rules.uploadedAgreement?.name||"Your company agreement")}</h2><p>This Vehicle Rental Agreement is entered into by <mark>{company||"[Company Name]"}</mark> (“Owner”) and <mark>[Renter Name]</mark> (“Renter”) for the use of <mark>[Vehicle Year, Make, Model and VIN]</mark>.</p><p>{source==="stock"?<>The rental begins on <mark>[Pickup Date and Time]</mark> and is scheduled to end on <mark>[Return Date and Time]</mark>. Renter agrees to all rates, deposits, mileage, fuel, protection, use, inspection, and return terms shown in the completed agreement.</>:<>Your uploaded document remains the controlling agreement. Check Calling will use the reusable company and rental fields configured here when preparing its signing package.</>}</p><p className="preview-note">Every bracketed field is filled from the business, renter, vehicle, payment, and reservation records before signing.</p></aside></section>
    <section className="agreement-card"><div className="agreement-card-head"><div><span>Delivery & automation</span><h2>Signing and vehicle-release workflow</h2></div><em>Connected journey</em></div><div className="agreement-fields"><label>E-signature provider<select name="signatureProvider" defaultValue={rules.signatureProvider??"check_calling"}><option value="check_calling">Check Calling embedded signature</option><option value="docusign">DocuSign</option><option value="adobe_sign">Adobe Acrobat Sign</option><option value="dropbox_sign">Dropbox Sign</option></select></label><label>Send agreement<select name="sendTiming" defaultValue={rules.sendTiming??"approval"}><option value="approval">After renter approval</option><option value="payment">After first payment</option><option value="manual">When host sends it</option></select></label><label>Reminder interval<input name="reminderHours" type="number" min="1" max="168" defaultValue={rules.reminderHours??24}/><small>Hours between signing reminders</small></label></div><div className="agreement-checks"><label><input type="checkbox" name="requireSignature" defaultChecked={rules.requireSignature??true}/>Require signed agreement before release</label><label><input type="checkbox" name="requirePayment" defaultChecked={rules.requirePayment??true}/>Require first payment</label><label><input type="checkbox" name="requireDeposit" defaultChecked={rules.requireDeposit??true}/>Require deposit authorization</label><label><input type="checkbox" name="requireInspection" defaultChecked={rules.requireInspection??true}/>Require pre-trip inspection</label><label><input type="checkbox" name="includeEvaluationSummary" defaultChecked={rules.includeEvaluationSummary}/>Include approved conditions from Renter Evaluation</label></div></section>
    <div className="agreement-legal"><strong>Template review required</strong><p>Stock agreements are configurable operational templates and are not jurisdiction-specific legal advice. The host should have its final agreement reviewed for its location, rental model, and insurance requirements before launch.</p></div><div className="agreement-save"><p>Saving creates the reusable agreement configuration used by the renter journey and completed rental package.</p><button>Save agreement setup</button></div>
  </form>;
}
