"use client";
import { useState } from "react";
import { savePaymentRules } from "./actions";

type TaxProfile = { name:string; rate:number; appliesTo:string };
export type PaymentRules = { provider?:string;currency?:string;rentalBilling?:string;acceptCards?:boolean;acceptWallets?:boolean;automaticReceipts?:boolean;payoutSchedule?:string;baseDeposit?:number;damageHold?:number;captureTiming?:string;taxInclusive?:boolean;defaultTaxProfile?:string;taxProfiles?:TaxProfile[];requireProtectionChoice?:boolean;allowPersonalInsurance?:boolean;protectionPlan?:string;incidentDeductible?:number };

export default function PaymentsForm({ rules }: { rules:PaymentRules }) {
  const [taxes,setTaxes] = useState<TaxProfile[]>(rules.taxProfiles?.length?rules.taxProfiles:[{name:"Sales Tax",rate:0,appliesTo:"rental"}]);
  const updateTax=(index:number,key:keyof TaxProfile,value:string|number)=>setTaxes(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));
  return <form action={savePaymentRules} className="payments-form">
    <section className="payments-card"><div className="payments-card-head"><div><span>Payment processing</span><h2>Collect charges and send payouts</h2></div><em>Connection required</em></div><div className="provider-card"><div className="provider-logo">$</div><div><strong>Choose a payment processor</strong><p>Authorize the selected provider after deployment to collect payments, hold deposits, issue refunds, and send payouts. Private account keys are never entered on this page.</p></div><button type="button" disabled>Connect after deployment</button></div><div className="payments-grid"><label>Payment provider<select name="provider" defaultValue={rules.provider??"stripe"}><option value="stripe">Stripe Connect</option><option value="paypal">PayPal / Braintree</option><option value="square">Square</option><option value="adyen">Adyen</option><option value="authorize_net">Authorize.Net</option></select></label><label>Settlement currency<select name="currency" defaultValue={rules.currency??"USD"}><option value="USD">USD — US Dollar</option><option value="CAD">CAD — Canadian Dollar</option><option value="EUR">EUR — Euro</option></select></label><label>Payout schedule<select name="payoutSchedule" defaultValue={rules.payoutSchedule??"daily"}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="manual">Manual</option></select></label><label>Rental billing schedule<select name="rentalBilling" defaultValue={rules.rentalBilling??"per_rental"}><option value="per_rental">Charge each rental</option><option value="weekly">Weekly rental billing</option><option value="monthly">Monthly rental billing</option></select></label></div><div className="payment-checks"><label><input type="checkbox" name="acceptCards" defaultChecked={rules.acceptCards??true}/>Accept credit and debit cards</label><label><input type="checkbox" name="acceptWallets" defaultChecked={rules.acceptWallets??true}/>Accept supported digital wallets</label><label><input type="checkbox" name="automaticReceipts" defaultChecked={rules.automaticReceipts??true}/>Send automatic payment receipts</label></div></section>
    <section className="payments-card"><div className="payments-card-head"><div><span>Deposits & authorizations</span><h2>Protect each rental</h2></div><em>Host controlled</em></div><div className="payments-grid"><label>Base security deposit<input name="baseDeposit" type="number" min="0" step="25" defaultValue={rules.baseDeposit??500}/></label><label>Damage authorization hold<input name="damageHold" type="number" min="0" step="25" defaultValue={rules.damageHold??500}/></label><label>Capture first rental payment<select name="captureTiming" defaultValue={rules.captureTiming??"booking"}><option value="booking">When booking is confirmed</option><option value="pickup">At vehicle pickup</option><option value="manual">Host confirms manually</option></select></label></div></section>
    <section className="payments-card"><div className="payments-card-head"><div><span>Taxes & fees</span><h2>Tax profiles</h2></div><button type="button" className="add-tax" onClick={()=>setTaxes(items=>[...items,{name:"",rate:0,appliesTo:"rental"}])}>＋ Add tax profile</button></div><p>Create reusable profiles for rentals, add-ons, delivery, or all taxable charges.</p><div className="tax-head"><span>Profile name</span><span>Percentage</span><span>Applies to</span><span/></div>{taxes.map((tax,index)=><div className="tax-row" key={index}><input name="taxName" value={tax.name} onChange={e=>updateTax(index,"name",e.target.value)} placeholder="Sales Tax"/><input name="taxRate" type="number" min="0" max="100" step="0.001" value={tax.rate} onChange={e=>updateTax(index,"rate",Number(e.target.value))}/><select name="taxAppliesTo" value={tax.appliesTo} onChange={e=>updateTax(index,"appliesTo",e.target.value)}><option value="rental">Rental charges</option><option value="addons">Add-ons</option><option value="delivery">Delivery fees</option><option value="all">All taxable charges</option></select><button type="button" onClick={()=>setTaxes(items=>items.filter((_,i)=>i!==index))}>Remove</button></div>)}<div className="payments-grid tax-options"><label>Default tax profile<select name="defaultTaxProfile" defaultValue={rules.defaultTaxProfile??""}><option value="">Choose when profiles are saved</option>{taxes.filter(t=>t.name).map((tax,index)=><option key={`${tax.name}-${index}`} value={tax.name}>{tax.name}</option>)}</select></label><label className="check-card"><input type="checkbox" name="taxInclusive" defaultChecked={rules.taxInclusive}/>Display prices with tax included</label></div></section>
    <section className="payments-card"><div className="payments-card-head"><div><span>Protection</span><h2>Coverage choices and incident responsibility</h2></div><em>Rental safeguards</em></div><div className="payments-grid"><label>Default protection option<select name="protectionPlan" defaultValue={rules.protectionPlan??"standard"}><option value="standard">Standard protection</option><option value="premium">Premium protection</option><option value="host_defined">Host-defined coverage</option></select></label><label>Incident deductible<input name="incidentDeductible" type="number" min="0" step="50" defaultValue={rules.incidentDeductible??1000}/></label></div><div className="payment-checks"><label><input type="checkbox" name="requireProtectionChoice" defaultChecked={rules.requireProtectionChoice??true}/>Require the renter to choose a protection option</label><label><input type="checkbox" name="allowPersonalInsurance" defaultChecked={rules.allowPersonalInsurance??true}/>Allow verified personal insurance</label></div></section>
    <div className="payments-save"><p>These settings become the financial policy used by checkout, agreements, recommendations, and rental workflows.</p><button>Save payment, tax & protection rules</button></div>
  </form>;
}
