"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

async function context(vehicleId:string){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const {data:vehicle}=await supabase.from("vehicles").select("id,organization_id").eq("id",vehicleId).maybeSingle();if(!vehicle)redirect("/dashboard");return{supabase,user,vehicle};}
const date=(value:FormDataEntryValue|null)=>String(value||"")||null;

export async function saveOperationalProfile(vehicleId:string,formData:FormData){const {supabase,user,vehicle}=await context(vehicleId);const payload={vehicle_id:vehicleId,organization_id:vehicle.organization_id,registration_state:String(formData.get("registration_state")||"").trim(),registration_expires_on:date(formData.get("registration_expires_on")),insurance_provider:String(formData.get("insurance_provider")||"").trim(),insurance_policy:String(formData.get("insurance_policy")||"").trim(),insurance_expires_on:date(formData.get("insurance_expires_on")),inspection_expires_on:date(formData.get("inspection_expires_on")),next_service_on:date(formData.get("next_service_on")),next_service_odometer:Number(formData.get("next_service_odometer"))||null,title_status:String(formData.get("title_status")||"").trim(),warranty_expires_on:date(formData.get("warranty_expires_on")),roadside_provider:String(formData.get("roadside_provider")||"").trim(),updated_by:user.id,updated_at:new Date().toISOString()};const {error}=await supabase.from("vehicle_operational_profiles").upsert(payload,{onConflict:"vehicle_id"});if(error)redirect(`/dashboard/fleet/${vehicleId}?error=${encodeURIComponent(error.message)}#record-inputs`);revalidatePath(`/dashboard/fleet/${vehicleId}`);redirect(`/dashboard/fleet/${vehicleId}?saved=operational#record-inputs`);}

export async function addRentalActivity(vehicleId:string,formData:FormData){const {supabase,user,vehicle}=await context(vehicleId);const starts=String(formData.get("starts_at")||""),ends=String(formData.get("ends_at")||"");if(!starts||!ends||new Date(ends)<=new Date(starts))redirect(`/dashboard/fleet/${vehicleId}?error=Enter+a+valid+rental+start+and+end.#rental-history`);const {error}=await supabase.from("vehicle_rental_activity").insert({organization_id:vehicle.organization_id,vehicle_id:vehicleId,source:"manual",reference_number:String(formData.get("reference_number")||""),starts_at:new Date(starts).toISOString(),ends_at:new Date(ends).toISOString(),revenue:Number(formData.get("revenue"))||0,platform_fees:Number(formData.get("platform_fees"))||0,start_odometer:Number(formData.get("start_odometer"))||null,end_odometer:Number(formData.get("end_odometer"))||null,status:"completed",created_by:user.id});if(error)redirect(`/dashboard/fleet/${vehicleId}?error=${encodeURIComponent(error.message)}#rental-history`);revalidatePath(`/dashboard/fleet/${vehicleId}`);redirect(`/dashboard/fleet/${vehicleId}?saved=rental#rental-history`);}

export async function uploadVehicleDocument(vehicleId:string,formData:FormData){const {supabase,user,vehicle}=await context(vehicleId);const file=formData.get("document");if(!(file instanceof File)||!file.size)redirect(`/dashboard/fleet/${vehicleId}?error=Choose+a+document.#vehicle-documents`);if(file.size>10*1024*1024)redirect(`/dashboard/fleet/${vehicleId}?error=Document+must+be+under+10+MB.#vehicle-documents`);const ext=(file.name.split(".").pop()||"pdf").replace(/[^a-z0-9]/gi,"");const path=`${vehicle.organization_id}/${vehicleId}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await supabase.storage.from("vehicle-documents").upload(path,file,{contentType:file.type});if(uploadError)redirect(`/dashboard/fleet/${vehicleId}?error=${encodeURIComponent(uploadError.message)}#vehicle-documents`);const {error}=await supabase.from("vehicle_documents").insert({organization_id:vehicle.organization_id,vehicle_id:vehicleId,document_type:String(formData.get("document_type")||"other"),storage_path:path,file_name:file.name,expires_on:date(formData.get("expires_on")),created_by:user.id});if(error)redirect(`/dashboard/fleet/${vehicleId}?error=${encodeURIComponent(error.message)}#vehicle-documents`);revalidatePath(`/dashboard/fleet/${vehicleId}`);redirect(`/dashboard/fleet/${vehicleId}?saved=document#vehicle-documents`);}
